name: Checkov Custom Checks

on:
  push:
    branches: [ main ]
    paths:
      - 'examples/**'
      - 'custom_checks/**'
      - '.github/workflows/checkov.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'examples/**'
      - 'custom_checks/**'
      - '.github/workflows/checkov.yml'
  workflow_dispatch:

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Cache uv
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/uv
            ~/.cargo/bin/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install uv
        run: |
          if ! command -v uv &> /dev/null; then
            curl -LsSf https://astral.sh/uv/install.sh | sh
          fi
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install checkov jq

      - name: Run Checkov on examples (optimized)
        id: run_checkov
        run: |
          source .venv/bin/activate
          
          # Create a list of all example files
          EXAMPLE_FILES=$(find ./examples -name "example_*.tf" | sort)
          
          # Initialize summary variables
          TOTAL_CHECKS=0
          PASSED_CHECKS=0
          EXPECTED_FAILED_CHECKS=0
          UNEXPECTED_FAILED_CHECKS=0
          SUMMARY=""
          
          # Process files in batches for better performance
          # Group files by check ID to reduce the number of Checkov runs
          declare -A CHECK_FILES
          
          for file_path in $EXAMPLE_FILES; do
            filename=$(basename "$file_path")
            CHECK_NUM=$(echo $filename | cut -d'_' -f2)
            CHECK_ID="CKV_AWSCC_${CHECK_NUM}"
            
            if [ -z "${CHECK_FILES[$CHECK_ID]}" ]; then
              CHECK_FILES[$CHECK_ID]="$file_path"
            else
              CHECK_FILES[$CHECK_ID]="${CHECK_FILES[$CHECK_ID]} $file_path"
            fi
          done
          
          # Run Checkov once per check ID on all relevant files
          for CHECK_ID in "${!CHECK_FILES[@]}"; do
            echo "Running Checkov for $CHECK_ID"
            FILES="${CHECK_FILES[$CHECK_ID]}"
            
            # Count expected failures in these files
            EXPECTED_FAILURES=$(grep -c "fail" $FILES || echo "0")
            
            # Run checkov on all files for this check ID
            OUTPUT=$(checkov -f $FILES --external-checks-dir ./custom_checks --check $CHECK_ID -o json || true)
            
            # Parse the JSON output
            PASSED=$(echo $OUTPUT | jq '.summary.passed' 2>/dev/null || echo "0")
            FAILED=$(echo $OUTPUT | jq '.summary.failed' 2>/dev/null || echo "0")
            
            # Ensure values are integers
            PASSED=${PASSED:-0}
            FAILED=${FAILED:-0}
            EXPECTED_FAILURES=${EXPECTED_FAILURES:-0}
            
            # Update counters
            TOTAL_CHECKS=$((TOTAL_CHECKS + PASSED + FAILED))
            PASSED_CHECKS=$((PASSED_CHECKS + PASSED))
            
            # Check if failures were expected
            if [ "$FAILED" -gt 0 ]; then
              if [ "$EXPECTED_FAILURES" -gt 0 ]; then
                EXPECTED_FAILED_CHECKS=$((EXPECTED_FAILED_CHECKS + FAILED))
                echo "Found $FAILED expected failures for $CHECK_ID"
              else
                UNEXPECTED_FAILED_CHECKS=$((UNEXPECTED_FAILED_CHECKS + FAILED))
                echo "Found $FAILED UNEXPECTED failures for $CHECK_ID"
                # Fail the workflow if there are unexpected failures
                exit 1
              fi
            fi
            
            # Add to summary
            CHECK_NAME=$(echo $FILES | xargs -n1 basename | head -1 | cut -d'_' -f3- | sed 's/\.tf$//')
            SUMMARY="${SUMMARY}| ${CHECK_ID} | ${CHECK_NAME} | ${PASSED} | ${FAILED} | ${EXPECTED_FAILURES} |\n"
          done
          
          # Create GitHub step summary
          echo "## Checkov Custom Checks Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Total checks run: $TOTAL_CHECKS" >> $GITHUB_STEP_SUMMARY
          echo "Passed checks: $PASSED_CHECKS" >> $GITHUB_STEP_SUMMARY
          echo "Expected failed checks: $EXPECTED_FAILED_CHECKS" >> $GITHUB_STEP_SUMMARY
          echo "Unexpected failed checks: $UNEXPECTED_FAILED_CHECKS" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Check ID | Check Name | Passed | Failed | Expected Failures |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|------------|--------|--------|-------------------|" >> $GITHUB_STEP_SUMMARY
          echo -e "$SUMMARY" >> $GITHUB_STEP_SUMMARY
          
          # Set output for the job
          echo "passed_checks=$PASSED_CHECKS" >> $GITHUB_OUTPUT
          echo "expected_failed_checks=$EXPECTED_FAILED_CHECKS" >> $GITHUB_OUTPUT
          echo "unexpected_failed_checks=$UNEXPECTED_FAILED_CHECKS" >> $GITHUB_OUTPUT
